"""Regenerate docs/appendix.md from the vocabularies themselves.

The pair list is the archive's whole address space and it lives in three
places -- a prompt section and two bench modules. Transcribing it into docs
would guarantee drift, so the doc is generated: run this after any change to
cataloger.txt's vocabulary, lean_vocab.py or terse_vocab.py.

  python appendix.py
"""
import io, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bench
from topic_gloss import GLOSS
from lean_vocab import LEAN, LEAN_GLOSS
from terse_vocab import TERSE, TERSE_GLOSS, TIES

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "docs", "appendix.md")

SHELVES = [
    ("Shipped", bench.VOCAB, GLOSS, """\
The vocabulary in `src/EciCas.Host/instructions/cataloger.txt`, and the shelf
everything up to batch 8 was measured on. Concrete folder names: `passport`
is already the word a question uses, which is why the gloss measured at zero
here."""),
    ("Terse", TERSE, TERSE_GLOSS, """\
`tools/retrieval-bench/terse_vocab.py`. Seven categories cut by SUBJECT and
one, `appointment`, cut by TIME -- the only orthogonal drawer, because
"future and committed" changes what you do with a fact where a place or a
subject does not.

The names are abstract where the shipped ones were concrete, which is the
whole reason the gloss matters more here. Not shipped and not yet measured:
the filing comparison against the shipped shelf, both arms with and without
the gloss, is the batch this shelf was built for."""),
    ("Lean", LEAN, LEAN_GLOSS, """\
`tools/retrieval-bench/lean_vocab.py`. The first cut at consolidation, kept
because batches 3-7 are measured on it and those numbers cannot be read
against a shelf it was not run on. Superseded by Terse."""),
]


def main():
    o = io.StringIO()
    w = o.write
    w("""# Appendix — the category/topic pairs

The file name is the index. One parquet file per `(Category, Topic)`, no
subject index, so this list is the whole address space the archive has: a
fact filed outside it is not findable, and a pair the Librarian is never
shown is not openable.

`other` closes every category on every shelf. It is write-side only -- the
Cataloger may file into it, the Librarian is never shown it, and code opens
it beside its parent category. It carries no gloss anywhere, by design: a
definition would make it a folder that is about something, and its whole job
is to be the one that is not.

The gloss words are in the QUESTION's vocabulary, not the folder's. A gloss
that explains what a topic means to a librarian is worthless; both stages
match a turn against a name, so the gloss has to contain the words the turn
would actually use.

Generated by `tools/retrieval-bench/appendix.py`. Do not edit by hand.

| shelf | categories | pairs | folders | glossed |
|---|---|---|---|---|
""")
    for name, v, g, _ in SHELVES:
        pairs = sum(len(x) for x in v.values())
        w("| %s | %d | %d | %d | %d |\n" % (
            name.lower(), len(v), pairs, pairs - len(v),
            sum(len(x) for x in g.values())))

    w("\n## Tie rules (Terse)\n\n")
    w("""The rules a merge cannot carry on its own. Each is a tie the writer meets on
the terse shelf and cannot resolve from the folder names alone, which is what
`cataloger.txt` already does for the manager case -- a tie rule nothing
enforces is a comment.

""")
    for para in TIES.strip().split("\n\n"):
        w("- " + " ".join(para.split()) + "\n")

    for name, v, g, note in SHELVES:
        pairs = sum(len(x) for x in v.values())
        w("\n## %s — %d pairs\n\n%s\n\n" % (name, pairs, note))
        for c in v:
            w("### %s (%d)\n\n" % (c, len(v[c])))
            for t in v[c]:
                words = g.get(c, {}).get(t)
                w("- `%s/%s`%s\n" % (c, t, " — " + words if words else ""))
            w("\n")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(o.getvalue())
    print("wrote %s (%d lines)" % (OUT, o.getvalue().count("\n")))


if __name__ == "__main__":
    main()
