# A few words of gloss per topic, for the selector's index only.
#
# The baseline says the reader gets the category right 79% of the time and
# the pair only 36%. The misses are not confusion about the drawer, they are
# a coin-flip between two or three folders inside it that mean nearly the
# same thing -- licence/renewal/certificate/deadline, appliance/repair/tool,
# course/university/qualification.
#
# The words are chosen in the QUESTION's vocabulary, not the folder's. A
# gloss that explains what a topic means to a librarian is worthless; the
# selector is matching a turn against a name, so the gloss has to contain the
# words a person would actually use when asking. "renewal (expires, expiry,
# renew, valid until)" is here because the baseline miss was literally "When
# does my licence expire?" opening admin/licence.
#
# Deliberately not shown to Cataloger. Filing is not what is failing, and
# changing both sides at once would mean a moved number has two possible
# parents and the archive has to be rebuilt. This arm changes what the
# selector reads and nothing else.
#
# Two known risks, both from librarian.txt's own history:
#   * a word in a gloss promotes that topic even when the sentence denies it
#     -- naming a counter-example is naming a candidate;
#   * more tokens in the index is a longer prompt, and the selector already
#     reads ~160 lines.
# Both are why this is measured rather than shipped.
GLOSS = {
 "identity": {
  "name": "called, full name, spelling",
  "age": "how old, birthday year, born",
  "birth": "born, birthplace, date of birth",
  "origin": "from, grew up, hometown",
  "nationality": "citizen, passport country",
  "language": "speaks, fluent, mother tongue",
  "appearance": "looks, height, hair, glasses",
  "personality": "temperament, character, introvert",
  "belief": "thinks, opinion, worldview",
  "religion": "faith, church, practising",
  "politics": "votes, party, political",
  "value": "matters to, principle, cares about",
  "fear": "afraid, scared, phobia, terrified",
  "preference": "likes, prefers, favourite, hates",
  "allegiance": "supports, fan of, team loyalty",
  "habit": "always, usually, tends to",
  "humour": "jokes, finds funny",
 },
 "body": {
  "condition": "illness, chronic, suffers from, seasick",
  "injury": "broke, sprained, hurt, accident",
  "allergy": "allergic, reaction, intolerant",
  "medication": "takes, prescription, pills, dose",
  "diet": "eats, avoids, vegetarian, cannot eat",
  "sleep": "bedtime, insomnia, hours slept",
  "fitness": "exercise, training, gym, running",
  "weight": "kilos, heavier, lost weight",
  "vision": "eyesight, glasses, lenses",
  "hearing": "deaf, hearing aid, ears",
  "dental": "teeth, dentist, filling",
  "mental": "anxiety, stress, therapy, mood",
  "practitioner": "doctor, GP, specialist, clinic",
  "appointment": "booked, seeing the doctor, scheduled",
  "treatment": "surgery, therapy, course of",
  "vaccination": "jab, vaccinated, booster",
  "symptom": "pain, ache, feels, dizzy",
 },
 "household": {
  "property": "house, flat, own, rent, mortgage",
  "room": "kitchen, bedroom, upstairs",
  "garden": "outside, lawn, plants, shed",
  "furniture": "sofa, table, bed, wardrobe",
  "appliance": "washing machine, dishwasher, heat pump, boiler, fridge",
  "electronics": "tv, laptop, phone, router",
  "vehicle": "car, drives, bike, van",
  "tool": "drill, ladder, toolbox",
  "maintenance": "serviced, installed, checked, upkeep",
  "repair": "broken, leaks, fix, fault",
  "cleaning": "tidy, hoover, laundry",
  "utility": "power, water, heating, broadband",
  "pet": "dog, cat, walks, feeds",
  "plant": "watering, indoor plants",
  "storage": "attic, cellar, boxes, keeps",
  "decor": "paint, curtains, pictures",
  "address": "lives at, where is, located, nearby, spare key",
 },
 "relations": {
  "family": "relatives, household, our family",
  "parent": "mother, father, mum, dad",
  "sibling": "brother, sister",
  "child": "son, daughter, kids",
  "partner": "wife, husband, spouse, girlfriend",
  "friend": "mate, best friend, pal",
  "colleague": "co-worker, workmate, manager, boss",
  "neighbour": "next door, up the road, nearby",
  "birthday": "turns, born in, birthday",
  "anniversary": "wedding, years together",
  "contact": "number, email, how to reach",
  "conflict": "fell out, argument, not speaking",
  "care": "looks after, helps, elderly",
  "gift": "present, bought for, wants",
  "visit": "drop by, staying with, coming over",
  "history": "passed away, used to, back then, died",
 },
 "work": {
  "employer": "works at, company, firm",
  "role": "job title, position, works as",
  "duty": "responsible for, handles, does",
  "project": "working on, deadline, deliverable",
  "schedule": "shifts, hours, days worked",
  "location": "office, site, works from",
  "commute": "gets to work, bus, train, drive in",
  "meeting": "standup, review, calls",
  "client": "customer, account",
  "performance": "review, feedback, appraisal",
  "promotion": "raise, promoted, step up",
  "leave": "holiday days, sick leave, off",
  "career": "years at, background, path",
  "workplace": "the office itself, desk, building",
  "tool": "software, system, uses at work",
  "history": "used to work, previous job, how long",
 },
 "money": {
  "income": "earns, comes in, revenue",
  "salary": "paid, wage, monthly pay",
  "payday": "paid on, the 15th, end of month",
  "expense": "spends, costs, outgoings",
  "bill": "invoice, utility bill, due",
  "subscription": "monthly, streaming, membership fee",
  "debt": "owes, credit card",
  "loan": "borrowed, repayment",
  "mortgage": "house loan, interest, term",
  "saving": "saving for, put aside, rainy day",
  "investment": "shares, fund, stocks",
  "pension": "retirement, contributions",
  "budget": "affordable, spending plan",
  "purchase": "bought, buying, spend on",
  "price": "costs, how much",
  "tax": "tax return, deduction",
  "benefit": "allowance, support payment",
 },
 "learning": {
  "school": "at school, pupil, class, taught",
  "university": "degree at, studied at, campus, uit, ntnu",
  "course": "enrolled, module, evening class",
  "subject": "field, discipline, studied what",
  "qualification": "masters, bachelor, degree in, diploma",
  "exam": "test, sat, results",
  "skill": "can do, learned to, good at",
  "language": "speaks, learning, fluent",
  "teacher": "tutor, lecturer, instructor",
  "study": "revising, reading up, learning",
  "book": "textbook, reading for study",
  "certification": "certified, licence to practise",
  "plan": "wants to study, applying",
  "progress": "getting on, halfway through",
 },
 "leisure": {
  "hobby": "does for fun, pastime, gave up",
  "sport": "plays, runs, skis, swims",
  "team": "supports, plays for, club side",
  "music": "listens, sings, choir, band",
  "instrument": "plays bass, guitar, piano",
  "game": "board games, video games, chess",
  "reading": "reads, novels, author, books",
  "film": "watches, cinema, movies",
  "television": "series, watches, streaming",
  "cooking": "cooks, bakes, recipes",
  "outdoor": "hiking, cabin trips, fishing",
  "craft": "knitting, woodwork, making",
  "club": "member of, meets, society",
  "event": "concert, festival, going to",
  "routine": "every week, on Wednesdays, before breakfast, regularly",
  "social": "meets up, pub, friends round",
  "collection": "collects, owns a set of",
 },
 "travel": {
  "trip": "went to, going to, journey",
  "destination": "place visited, where to",
  "accommodation": "hotel, cabin, stays at",
  "flight": "flies, airline, airport",
  "transport": "train, ferry, boat, car hire, bus",
  "booking": "booked, reserved, confirmed",
  "plan": "planning to go, itinerary",
  "visit": "visiting, seeing people, dropping in",
  "holiday": "summer holiday, break, vacation",
  "luggage": "packs, suitcase, bag",
  "companion": "travels with, goes with",
  "experience": "loved it, what happened there",
  "preference": "likes travelling by, avoids",
  "frequency": "often, once a year, rarely",
 },
 "admin": {
  "passport": "passport, travel document",
  "licence": "driving licence, permit",
  "insurance": "policy, covered, premium",
  "contract": "signed, agreement, terms",
  "account": "login, bank account, profile",
  "membership": "member of, subscription to",
  "registration": "registered, enrolled, on file",
  "warranty": "guarantee, covered until",
  "certificate": "certificate, official document",
  "renewal": "expires, expiry, renew, runs out, valid until, needs renewing",
  "deadline": "due by, must be done by, cut-off",
  "provider": "supplier, company used, switched to",
  "will": "testament, inheritance",
  "document": "papers, forms, filed",
  "reference": "reference number, case id",
 },
}
